#!/bin/bash
COMPLETION_DIR=$ENV_CONF_HOME/sh/completions

if [ -d $COMPLETION_DIR ]; then
    for file in $(\ls $COMPLETION_DIR); do
	if [[ $file != *~ ]]; then
	    . ${COMPLETION_DIR}/$file
	fi
    done
fi
