#!/bin/bash 

_github_compl(){
    local cur=${COMP_WORDS[$COMP_CWORD]}

    case $COMP_CWORD in
        1)
            variables=$( cat $HOME/bin/github | grep -E 'https?://' | cut -d'=' -f 1 )
            COMPREPLY=( $(compgen -W "$variables") )
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _github_compl github
